spring:
  cloud:
    gateway:
      #mvc:
       routes:
         - id: r1
           uri: lb://CUSTOMER-SERVICE
           #uri: http://localhost:8081
           predicates:
            Path= /api/customers/**
         - id: r2
           #uri: http://localhost:8082
           uri: lb://INVENTORY-SERVICE
           predicates:
            Path= /api/products/**